services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: coffeeshop
      POSTGRES_USER: adminopswat
      POSTGRES_PASSWORD: adminopswatpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  product:
    image: cuongopswat/go-coffeeshop-product
    container_name: product
    environment:
      APP_NAME: product-service
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - rabbitmq

  counter:
    image: cuongopswat/go-coffeeshop-counter
    container_name: counter
    environment:
      APP_NAME: counter-service
      IN_DOCKER: "true"
      PG_URL: postgres://adminopswat:adminopswatpass@postgres:5432/coffeeshop
      PG_DSN_URL: host=postgres user=adminopswat password=adminopswatpass dbname=coffeeshop sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PRODUCT_CLIENT_URL: product:5001
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - rabbitmq
      - product

  proxy:
    image: cuongopswat/go-coffeeshop-proxy
    container_name: proxy
    environment:
      APP_NAME: proxy-service
      GRPC_PRODUCT_HOST: product
      GRPC_PRODUCT_PORT: 5001
      GRPC_COUNTER_HOST: counter
      GRPC_COUNTER_PORT: 5002
    ports:
      - "5000:5000"
    depends_on:
      - counter
      - product

  web:
    image: cuongopswat/go-coffeeshop-web
    container_name: web
    environment:
      REVERSE_PROXY_URL: http://proxy:5000
      WEB_PORT: 8888
    ports:
      - "8888:8888"
    depends_on:
      - proxy

  barista:
    image: cuongopswat/go-coffeeshop-barista
    container_name: barista
    environment:
      APP_NAME: barista-service
      IN_DOCKER: "true"
      PG_URL: postgres://adminopswat:adminopswatpass@postgres:5432/coffeeshop
      PG_DSN_URL: host=postgres user=adminopswat password=adminopswatpass dbname=coffeeshop sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq

  kitchen:
    image: cuongopswat/go-coffeeshop-kitchen
    container_name: kitchen
    environment:
      APP_NAME: kitchen-service
      IN_DOCKER: "true"
      PG_URL: postgres://adminopswat:adminopswatpass@postgres:5432/coffeeshop
      PG_DSN_URL: host=postgres user=adminopswat password=adminopswatpass dbname=coffeeshop sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
